[project]
name = "place-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "googlemaps>=4.10.0",
    "osmnx>=2.0.6",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
]

[project.scripts]
research = "place_research.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "isort>=6.0.1",
    "pytest>=8.4.1",
    "ruff>=0.12.10",
]
