[tool.poetry]
name = "place-research"
version = "0.1.0"
description = ""
authors = ["Lucas Howard <lhoward96@gmail.com>"]
readme = "README.md"
packages = [{ include = "place_research", from = "." }]

[tool.poetry.dependencies]
python = "^3.12"
googlemaps = "^4.10.0"
python-dotenv = "^1.0.1"
jupyter = "^1.0.0"
openpyxl = "^3.1.2"
pandas = "^2.2.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
black = "^24.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
